name: root_gorge
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  fields_api:
    path: packages/fields_api
  fields_repository:
    path: packages/fields_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_services_binding: ^0.1.0
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.3.2+1
  intl: ^0.17.0
  local_storage_fields_api:
    path: packages/local_storage_fields_api
  rxdart: ^0.27.3

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
