name: root_gorge
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  field_google_map:
    path: packages/field_google_map
  fields_api:
    path: packages/fields_api
  fields_repository:
    path: packages/fields_repository
  firebase_core: ^1.14.0
  firestore_fields_api:
    path: packages/firestore_fields_api
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  flutter_services_binding: ^0.1.0
  google_fonts: ^2.3.1
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: ^0.3.2+1
  intl: ^0.17.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mockingjay: ^0.2.0
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/corn-logo.png
    - assets/wheat-logo.png
    - assets/soybean-logo.png
    - assets/organic-logo.png
    - assets/gmo-logo.png
