name: root_gorge
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  cloud_firestore: ^3.1.18
  cupertino_icons: ^1.0.2
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  google_maps_flutter: ^2.1.8
  google_maps_flutter_web: ^0.4.0
  very_good_analysis: ^2.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/markers/corn-dicamba.png
    - assets/markers/corn-enlist.png
    - assets/markers/corn-roundup.png
    - assets/markers/corn-non-gmo.png
    - assets/markers/corn-organic.png
    - assets/markers/soybean-dicamba.png
    - assets/markers/soybean-enlist.png
    - assets/markers/soybean-roundup.png
    - assets/markers/soybean-non-gmo.png
    - assets/markers/soybean-organic.png
    - assets/markers/wheat-dicamba.png
    - assets/markers/wheat-enlist.png
    - assets/markers/wheat-roundup.png
    - assets/markers/wheat-non-gmo.png
    - assets/markers/wheat-organic.png
