name: authentication_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cache:
    path: ../../packages/cache
  equatable: ^2.0.3
  firebase_auth: ^3.0.2
  firebase_core: ^1.19.2
  flutter:
    sdk: flutter
  google_sign_in: ^5.4.0
  meta: ^1.7.0
  very_good_analysis: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
