name: firestore_fields_api
description: A Flutter implementation of the FieldsApi that uses Firebase Firestore storage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.11
  fields_api:
    path: ../fields_api
  firebase_core: ^1.14.0
  flutter:
    sdk: flutter
  meta: ^1.3.0
  rxdart: ^0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
